[uwsgi]
module = backend.wsgi:app
master = true
die-on-term = true
processes = 1
home = backend/venv
#remove for https
socket = 0.0.0.0:5000
#https = :5000,/etc/letsencrypt/live/followthatfred.com/fullchain.pem,/etc/letsencrypt/live/followthatfred.com/privkey.pem
